#!/usr/bin/bash

[ "${1}" ] && file=${1} || file=/dev/stdin

while [ "${file}" ]
do
        echo ${file}
        if [ ${file} != /dev/stdin ]
        then
                [ -L "${file}" ] && echo -n "cible  : " && readlink -e "${file}"
                stat -Lc "size   : %s" "${file}"
                stat -Lc "M date : %y" "${file}" | sed 's/\..*//'
                stat -Lc "A date : %x" "${file}" | sed 's/\..*//'
                stat -Lc "C date : %z" "${file}" | sed 's/\..*//'
        fi
        {
                tee < "${file}"                                        \
                    >( echo '1:xxh64  : '$(xxh64sum 2>/dev/null) >&3 ) \
                    >( echo '2:md5    : '$(md5sum) >&3 )               \
                    >( echo '3:sha1   : '$(sha1sum) >&3 )              \
                    >( echo '4:sha256 : '$(sha256sum) >&3 ) >/dev/null
        } 3>&1 | sort | sed -e 's/^.://g' -e 's/ -$//g'
        shift
        file=${1}
        [ "${file}" ] && echo
done
